export const galleryActionTypes = {
    GET_ALL_GALLERY_IMAGE_REQUEST: 'GET_ALL_GALLERY_IMAGE_REQUEST',
    GET_ALL_GALLERY_IMAGE_SUCCESS: 'GET_ALL_GALLERY_IMAGE_SUCCESS',
    GET_ALL_GALLERY_IMAGE_FAILURE: 'GET_ALL_GALLERY_IMAGE_FAILURE',

    GET_ALL_USER_IMAGE_REQUEST: 'GET_ALL_USER_IMAGE_REQUEST',
    GET_ALL_USER_IMAGE_SUCCESS: 'GET_ALL_USER_IMAGE_SUCCESS',
    GET_ALL_USER_IMAGE_FAILURE: 'GET_ALL_USER_IMAGE_FAILURE',

    UPLOAD_IMAGE_REQUEST: 'UPLOAD_IMAGE_REQUEST',
    UPLOAD_IMAGE_SUCCESS: 'UPLOAD_IMAGE_SUCCESS',
    UPLOAD_IMAGE_FAILURE: 'UPLOAD_IMAGE_FAILURE',

    DELETE_IMAGE_REQUEST: 'DELETE_IMAGE_REQUEST',
    DELETE_IMAGE_SUCCESS: 'DELETE_IMAGE_SUCCESS',
    DELETE_IMAGE_FAILURE: 'DELETE_IMAGE_FAILURE',
}